#!/usr/bin/env bash
echo "Installing your fave casks and background, Mindaugai. Beep Bøp"


#homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


BREW=(
cask
mas
ffmpeg
bandcamp-dl
youtube-dlc
)


CASKS=(
telegram
tyke
itsycal
toggl-track
vlc
slack 
fontforge
visual-studio-code
openoffice
google-chrome
microsoft-teams
)

#appstore
MAS=(
1320666476 #Wipr
)


brew install ${BREW[@]}

brew cask install ${CASKS[@]}

mas install ${MAS[@]}

#wallpaper
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/mindaugas/Pictures/roadtrip.jpg"'

echo "Complete. Beep Bøp"
