#!/usr/bin/env bash
echo "Installing your fave casks and background, Mindaugai. Beep Bøp"


#homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


BREW=(
cask
mas
ffmpeg
bandcamp-dl
exiftool
yt-dlp/taps/yt-dlp
)


CASKS=(
telegram
tyke
itsycal
toggl-track
vlc
obs
slack 
fontforge
visual-studio-code
openoffice
google-chrome
microsoft-teams
alt-tab
rectangle
)

#appstore
MAS=(
1320666476 #Wipr
)


brew install ${BREW[@]}

brew cask install ${CASKS[@]}

mas install ${MAS[@]}

#wallpaper
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/mindaugas/Pictures/roadtrip.jpg"'

echo "Complete. Beep Bøp"
